#!/usr/bin/env python3
"""page_data.py: data files the video page loads, for one video folder (build stage, in the cloud session).

Usage: python scripts/page_data.py V

Writes V/say.js (window.SAY: the narration of each segment, for subtitles and timing) and V/fonts/*.woff2
(Noto Sans CJK SC and DejaVu Sans Mono, cut down to the characters used by the page, so it renders offline).
Run it again after changing script.json or any text in the scenes. Needs: pip install fonttools brotli.
"""
import glob, json, os, sys
from fontTools.ttLib import TTCollection, TTFont
from fontTools import subset

CJK = {"Regular": "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
       "Bold": "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc"}
MONO = {"Regular": "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        "Bold": "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"}


def sc_font(path):
    for f in TTCollection(path).fonts:
        if any("Noto Sans CJK SC" == str(n) for n in f["name"].names if n.nameID == 1):
            return f
    sys.exit(f"no 'Noto Sans CJK SC' in {path}")


def cut(font, chars, out):
    opts = subset.Options(); opts.flavor = "woff2"; opts.layout_features = ["*"]
    s = subset.Subsetter(opts); s.populate(text=chars); s.subset(font)
    font.flavor = "woff2"; font.save(out)
    print(f"{out}: {os.path.getsize(out) // 1024} KB")


def main():
    v = sys.argv[1]
    script = json.load(open(os.path.join(v, "script.json"), encoding="utf-8"))
    say = {g["id"]: g["say"] for g in script["segments"]}
    with open(os.path.join(v, "say.js"), "w", encoding="utf-8") as f:
        f.write("// generated by page_data.py from script.json; do not edit by hand\n")
        f.write("window.SAY = " + json.dumps(say, ensure_ascii=False) + ";\n")
    text = "".join(say.values())
    for p in glob.glob(os.path.join(v, "*.js")) + glob.glob(os.path.join(v, "scenes", "*.js")):
        text += open(p, encoding="utf-8").read()
    chars = "".join(sorted(set(text) | set(map(chr, range(32, 127))) | set("…•→←↔≠✓✗×·–—“”‘’")))
    os.makedirs(os.path.join(v, "fonts"), exist_ok=True)
    for w, p in CJK.items():
        cut(sc_font(p), chars, os.path.join(v, "fonts", f"NotoSansSC-{w}.woff2"))
    for w, p in MONO.items():
        cut(TTFont(p), chars, os.path.join(v, "fonts", f"DejaVuSansMono-{w}.woff2"))


if __name__ == "__main__":
    main()
