#!/usr/bin/env node
// tex.mjs: typeset the video's formulas once, with MathJax, into SVG strings the page can draw on the canvas.
//
// Reads  <video folder>/formulas.json   { "id": "LaTeX", ... }  or  { "id": { "tex": "LaTeX", "color": "#hex" }, ... }
// Writes <video folder>/formulas.js     window.FORMULAS = { id: { svg, w, h, ascent } }   (w, h, ascent in em)
//
// Colour: the formula's default colour is "color" (else the page's INK, applied when drawn). Colour parts of a
// formula with {\color{#hex} x} inside the LaTeX. Put the braces AROUND it: \color is a switch that colours
// everything after it in the same group, so \color{#hex}{x} = y also colours "= y".
// Usage: node tex.mjs <video folder>      (run again whenever formulas.json changes)
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { mathjax } from 'mathjax-full/js/mathjax.js';
import { TeX } from 'mathjax-full/js/input/tex.js';
import { SVG } from 'mathjax-full/js/output/svg.js';
import { liteAdaptor } from 'mathjax-full/js/adaptors/liteAdaptor.js';
import { RegisterHTMLHandler } from 'mathjax-full/js/handlers/html.js';
import { AllPackages } from 'mathjax-full/js/input/tex/AllPackages.js';

const DIR = process.argv[2];
if (!DIR) { console.error('usage: node tex.mjs <video folder>'); process.exit(1); }
const IN = `${DIR}/formulas.json`, OUT = `${DIR}/formulas.js`;
if (!existsSync(IN)) { console.error(`${IN} not found`); process.exit(1); }
const src = JSON.parse(readFileSync(IN, 'utf8'));
const adaptor = liteAdaptor(); RegisterHTMLHandler(adaptor);
const doc = mathjax.document('', { InputJax: new TeX({ packages: AllPackages }), OutputJax: new SVG({ fontCache: 'none' }) });

const out = {}; let bad = 0;
for (const [id, v] of Object.entries(src)) {
  const tex = typeof v === 'string' ? v : v.tex, color = typeof v === 'string' ? null : v.color || null;
  const svg = adaptor.innerHTML(doc.convert(tex, { display: true }));
  if (/data-mjx-error|merror/.test(svg)) { console.error(`${id}: LaTeX error in  ${tex}`); bad++; continue; }
  const vb = svg.match(/viewBox="([-\d.]+) ([-\d.]+) ([-\d.]+) ([-\d.]+)"/).slice(1).map(Number);
  // drop MathJax's ex-based size; the page sets the pixel size when it draws
  const clean = svg.replace(/ style="[^"]*"/, '').replace(/ width="[^"]*"/, '').replace(/ height="[^"]*"/, '');
  out[id] = { svg: clean, color, w: vb[2] / 1000, h: vb[3] / 1000, ascent: -vb[1] / 1000 };
  console.log(`${id}: ${tex}`);
}
writeFileSync(OUT, '// generated by tex.mjs from formulas.json; do not edit by hand\nwindow.FORMULAS = ' + JSON.stringify(out) + ';\n');
console.log(`${Object.keys(out).length} formulas -> ${OUT}`);
if (bad) process.exit(1);
